/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
var common_data_common_pb = require('../common/data_common_pb.js');
goog.exportSymbol('proto.mktservice.OrganizationProfile', null, global);
goog.exportSymbol('proto.mktservice.OrganizationProfile.ExecutiveKey', null, global);
goog.exportSymbol('proto.mktservice.OrganizationProfile.ExecutiveKey.EPosition', null, global);
goog.exportSymbol('proto.mktservice.OrganizationProfile.StakeHolder', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.OrganizationProfile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mktservice.OrganizationProfile.repeatedFields_, null);
};
goog.inherits(proto.mktservice.OrganizationProfile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.OrganizationProfile.displayName = 'proto.mktservice.OrganizationProfile';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mktservice.OrganizationProfile.repeatedFields_ = [13,14];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.OrganizationProfile.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.OrganizationProfile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.OrganizationProfile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.OrganizationProfile.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticker: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    industry: jspb.Message.getFieldWithDefault(msg, 4, ""),
    language: jspb.Message.getFieldWithDefault(msg, 5, 0),
    listeddate: jspb.Message.getFieldWithDefault(msg, 10, ""),
    foreignownershippercentage: (f = msg.getForeignownershippercentage()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    foreignremainroompercentage: (f = msg.getForeignremainroompercentage()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    stakeholdersList: jspb.Message.toObjectList(msg.getStakeholdersList(),
    proto.mktservice.OrganizationProfile.StakeHolder.toObject, includeInstance),
    executivekeysList: jspb.Message.toObjectList(msg.getExecutivekeysList(),
    proto.mktservice.OrganizationProfile.ExecutiveKey.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.OrganizationProfile}
 */
proto.mktservice.OrganizationProfile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.OrganizationProfile;
  return proto.mktservice.OrganizationProfile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.OrganizationProfile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.OrganizationProfile}
 */
proto.mktservice.OrganizationProfile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setIndustry(value);
      break;
    case 5:
      var value = /** @type {!proto.mktservice.ELanguage} */ (reader.readEnum());
      msg.setLanguage(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setListeddate(value);
      break;
    case 11:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setForeignownershippercentage(value);
      break;
    case 12:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setForeignremainroompercentage(value);
      break;
    case 13:
      var value = new proto.mktservice.OrganizationProfile.StakeHolder;
      reader.readMessage(value,proto.mktservice.OrganizationProfile.StakeHolder.deserializeBinaryFromReader);
      msg.addStakeholders(value);
      break;
    case 14:
      var value = new proto.mktservice.OrganizationProfile.ExecutiveKey;
      reader.readMessage(value,proto.mktservice.OrganizationProfile.ExecutiveKey.deserializeBinaryFromReader);
      msg.addExecutivekeys(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.OrganizationProfile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.OrganizationProfile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.OrganizationProfile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.OrganizationProfile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIndustry();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLanguage();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getListeddate();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getForeignownershippercentage();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getForeignremainroompercentage();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getStakeholdersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.mktservice.OrganizationProfile.StakeHolder.serializeBinaryToWriter
    );
  }
  f = message.getExecutivekeysList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      proto.mktservice.OrganizationProfile.ExecutiveKey.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.OrganizationProfile.StakeHolder = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mktservice.OrganizationProfile.StakeHolder, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.OrganizationProfile.StakeHolder.displayName = 'proto.mktservice.OrganizationProfile.StakeHolder';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.OrganizationProfile.StakeHolder.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.OrganizationProfile.StakeHolder} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.OrganizationProfile.StakeHolder.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    ticker: jspb.Message.getFieldWithDefault(msg, 2, ""),
    language: jspb.Message.getFieldWithDefault(msg, 3, 0),
    shares: (f = msg.getShares()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    percentage: (f = msg.getPercentage()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.OrganizationProfile.StakeHolder}
 */
proto.mktservice.OrganizationProfile.StakeHolder.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.OrganizationProfile.StakeHolder;
  return proto.mktservice.OrganizationProfile.StakeHolder.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.OrganizationProfile.StakeHolder} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.OrganizationProfile.StakeHolder}
 */
proto.mktservice.OrganizationProfile.StakeHolder.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 3:
      var value = /** @type {!proto.mktservice.ELanguage} */ (reader.readEnum());
      msg.setLanguage(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setShares(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setPercentage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.OrganizationProfile.StakeHolder.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.OrganizationProfile.StakeHolder} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.OrganizationProfile.StakeHolder.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLanguage();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getShares();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getPercentage();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string Name = 1;
 * @return {string}
 */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string Ticker = 2;
 * @return {string}
 */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.setTicker = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional ELanguage Language = 3;
 * @return {!proto.mktservice.ELanguage}
 */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.getLanguage = function() {
  return /** @type {!proto.mktservice.ELanguage} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.mktservice.ELanguage} value */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.setLanguage = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.Int64Value Shares = 4;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.getShares = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 4));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.setShares = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.mktservice.OrganizationProfile.StakeHolder.prototype.clearShares = function() {
  this.setShares(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.hasShares = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.DoubleValue Percentage = 5;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.getPercentage = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 5));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.setPercentage = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.mktservice.OrganizationProfile.StakeHolder.prototype.clearPercentage = function() {
  this.setPercentage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.OrganizationProfile.StakeHolder.prototype.hasPercentage = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.OrganizationProfile.ExecutiveKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mktservice.OrganizationProfile.ExecutiveKey.repeatedFields_, null);
};
goog.inherits(proto.mktservice.OrganizationProfile.ExecutiveKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.OrganizationProfile.ExecutiveKey.displayName = 'proto.mktservice.OrganizationProfile.ExecutiveKey';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.OrganizationProfile.ExecutiveKey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.OrganizationProfile.ExecutiveKey} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.toObject = function(includeInstance, msg) {
  var f, obj = {
    fullname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    position: jspb.Message.getFieldWithDefault(msg, 2, ""),
    positiontypesList: jspb.Message.getRepeatedField(msg, 3),
    language: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.OrganizationProfile.ExecutiveKey}
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.OrganizationProfile.ExecutiveKey;
  return proto.mktservice.OrganizationProfile.ExecutiveKey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.OrganizationProfile.ExecutiveKey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.OrganizationProfile.ExecutiveKey}
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFullname(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPosition(value);
      break;
    case 3:
      var value = /** @type {!Array<!proto.mktservice.OrganizationProfile.ExecutiveKey.EPosition>} */ (reader.readPackedEnum());
      msg.setPositiontypesList(value);
      break;
    case 4:
      var value = /** @type {!proto.mktservice.ELanguage} */ (reader.readEnum());
      msg.setLanguage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.OrganizationProfile.ExecutiveKey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.OrganizationProfile.ExecutiveKey} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFullname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPosition();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPositiontypesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      3,
      f
    );
  }
  f = message.getLanguage();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.EPosition = {
  EPOS_UNSPECIFIED: 0,
  COFOUNDER: 8,
  CHAIRMAN: 1,
  VICEPRESIDENT: 2,
  PERMANENTVICECHAIRMAN: 3,
  MEMBEROFBOARDCHAIRMAN: 4,
  CHIEFOFSUPERVISORYBOARD: 5,
  DEPUTYOFSUPERVISORYBOARD: 6,
  MEMBEROFSUPERVISORYBOARD: 7,
  CHIEFEXCUTIVEOFFICER: 10,
  CHIEFACCOUNTANT: 11,
  DEPUTYCHIEFEXCUTIVEOFFICER: 12,
  PERMANENTDEPUTYCHIEFEXCUTIVEOFFICER: 13,
  SENIORMEMBEROFBOARDOFMANAGEMENT: 14,
  MEMBEROFBOARDOFMANAGEMENT: 15,
  CHIEFFINANCEOFFICER: 16,
  EXECUTIVEDIRECTOR: 17,
  OPERATIVEDIRECTOR: 18,
  CHIEFINFORMATIONOFFICER: 19,
  DIRECTOR: 38,
  STAFF: 39,
  CHEIFOFINTERNALAUDIT: 40,
  MEMBEROFINTERNALAUDIT: 41,
  INFOSUPPLIER: 42,
  CONTACTPERSION: 43
};

/**
 * optional string FullName = 1;
 * @return {string}
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.getFullname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.setFullname = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string Position = 2;
 * @return {string}
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.getPosition = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.setPosition = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated EPosition PositionTypes = 3;
 * @return {!Array<!proto.mktservice.OrganizationProfile.ExecutiveKey.EPosition>}
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.getPositiontypesList = function() {
  return /** @type {!Array<!proto.mktservice.OrganizationProfile.ExecutiveKey.EPosition>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<!proto.mktservice.OrganizationProfile.ExecutiveKey.EPosition>} value */
proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.setPositiontypesList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!proto.mktservice.OrganizationProfile.ExecutiveKey.EPosition} value
 * @param {number=} opt_index
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.addPositiontypes = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.clearPositiontypesList = function() {
  this.setPositiontypesList([]);
};


/**
 * optional ELanguage Language = 4;
 * @return {!proto.mktservice.ELanguage}
 */
proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.getLanguage = function() {
  return /** @type {!proto.mktservice.ELanguage} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.mktservice.ELanguage} value */
proto.mktservice.OrganizationProfile.ExecutiveKey.prototype.setLanguage = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional string Ticker = 1;
 * @return {string}
 */
proto.mktservice.OrganizationProfile.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationProfile.prototype.setTicker = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string Name = 2;
 * @return {string}
 */
proto.mktservice.OrganizationProfile.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationProfile.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string Description = 3;
 * @return {string}
 */
proto.mktservice.OrganizationProfile.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationProfile.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string Industry = 4;
 * @return {string}
 */
proto.mktservice.OrganizationProfile.prototype.getIndustry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationProfile.prototype.setIndustry = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional ELanguage Language = 5;
 * @return {!proto.mktservice.ELanguage}
 */
proto.mktservice.OrganizationProfile.prototype.getLanguage = function() {
  return /** @type {!proto.mktservice.ELanguage} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.mktservice.ELanguage} value */
proto.mktservice.OrganizationProfile.prototype.setLanguage = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string ListedDate = 10;
 * @return {string}
 */
proto.mktservice.OrganizationProfile.prototype.getListeddate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationProfile.prototype.setListeddate = function(value) {
  jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional google.protobuf.DoubleValue ForeignOwnershipPercentage = 11;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.OrganizationProfile.prototype.getForeignownershippercentage = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 11));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.OrganizationProfile.prototype.setForeignownershippercentage = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.mktservice.OrganizationProfile.prototype.clearForeignownershippercentage = function() {
  this.setForeignownershippercentage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.OrganizationProfile.prototype.hasForeignownershippercentage = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional google.protobuf.DoubleValue ForeignRemainRoomPercentage = 12;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.OrganizationProfile.prototype.getForeignremainroompercentage = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 12));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.OrganizationProfile.prototype.setForeignremainroompercentage = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.mktservice.OrganizationProfile.prototype.clearForeignremainroompercentage = function() {
  this.setForeignremainroompercentage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.OrganizationProfile.prototype.hasForeignremainroompercentage = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * repeated StakeHolder StakeHolders = 13;
 * @return {!Array<!proto.mktservice.OrganizationProfile.StakeHolder>}
 */
proto.mktservice.OrganizationProfile.prototype.getStakeholdersList = function() {
  return /** @type{!Array<!proto.mktservice.OrganizationProfile.StakeHolder>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mktservice.OrganizationProfile.StakeHolder, 13));
};


/** @param {!Array<!proto.mktservice.OrganizationProfile.StakeHolder>} value */
proto.mktservice.OrganizationProfile.prototype.setStakeholdersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.mktservice.OrganizationProfile.StakeHolder=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mktservice.OrganizationProfile.StakeHolder}
 */
proto.mktservice.OrganizationProfile.prototype.addStakeholders = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.mktservice.OrganizationProfile.StakeHolder, opt_index);
};


proto.mktservice.OrganizationProfile.prototype.clearStakeholdersList = function() {
  this.setStakeholdersList([]);
};


/**
 * repeated ExecutiveKey ExecutiveKeys = 14;
 * @return {!Array<!proto.mktservice.OrganizationProfile.ExecutiveKey>}
 */
proto.mktservice.OrganizationProfile.prototype.getExecutivekeysList = function() {
  return /** @type{!Array<!proto.mktservice.OrganizationProfile.ExecutiveKey>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mktservice.OrganizationProfile.ExecutiveKey, 14));
};


/** @param {!Array<!proto.mktservice.OrganizationProfile.ExecutiveKey>} value */
proto.mktservice.OrganizationProfile.prototype.setExecutivekeysList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.mktservice.OrganizationProfile.ExecutiveKey=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mktservice.OrganizationProfile.ExecutiveKey}
 */
proto.mktservice.OrganizationProfile.prototype.addExecutivekeys = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.mktservice.OrganizationProfile.ExecutiveKey, opt_index);
};


proto.mktservice.OrganizationProfile.prototype.clearExecutivekeysList = function() {
  this.setExecutivekeysList([]);
};


goog.object.extend(exports, proto.mktservice);
