/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_data_common_pb = require('../common/data_common_pb.js');
goog.exportSymbol('proto.mktservice.OrganizationEvent', null, global);
goog.exportSymbol('proto.mktservice.OrganizationEvents', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.OrganizationEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mktservice.OrganizationEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.OrganizationEvent.displayName = 'proto.mktservice.OrganizationEvent';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.OrganizationEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.OrganizationEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.OrganizationEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.OrganizationEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticker: jspb.Message.getFieldWithDefault(msg, 1, ""),
    announceddate: jspb.Message.getFieldWithDefault(msg, 2, ""),
    exdate: jspb.Message.getFieldWithDefault(msg, 3, ""),
    lastregisterdate: jspb.Message.getFieldWithDefault(msg, 4, ""),
    effectivedate: jspb.Message.getFieldWithDefault(msg, 5, ""),
    description: jspb.Message.getFieldWithDefault(msg, 6, ""),
    language: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.OrganizationEvent}
 */
proto.mktservice.OrganizationEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.OrganizationEvent;
  return proto.mktservice.OrganizationEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.OrganizationEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.OrganizationEvent}
 */
proto.mktservice.OrganizationEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnounceddate(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setExdate(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastregisterdate(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setEffectivedate(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = /** @type {!proto.mktservice.ELanguage} */ (reader.readEnum());
      msg.setLanguage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.OrganizationEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.OrganizationEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.OrganizationEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.OrganizationEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAnnounceddate();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExdate();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLastregisterdate();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getEffectivedate();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLanguage();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * optional string Ticker = 1;
 * @return {string}
 */
proto.mktservice.OrganizationEvent.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationEvent.prototype.setTicker = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string AnnouncedDate = 2;
 * @return {string}
 */
proto.mktservice.OrganizationEvent.prototype.getAnnounceddate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationEvent.prototype.setAnnounceddate = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string ExDate = 3;
 * @return {string}
 */
proto.mktservice.OrganizationEvent.prototype.getExdate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationEvent.prototype.setExdate = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string LastRegisterDate = 4;
 * @return {string}
 */
proto.mktservice.OrganizationEvent.prototype.getLastregisterdate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationEvent.prototype.setLastregisterdate = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string EffectiveDate = 5;
 * @return {string}
 */
proto.mktservice.OrganizationEvent.prototype.getEffectivedate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationEvent.prototype.setEffectivedate = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string Description = 6;
 * @return {string}
 */
proto.mktservice.OrganizationEvent.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationEvent.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional ELanguage Language = 7;
 * @return {!proto.mktservice.ELanguage}
 */
proto.mktservice.OrganizationEvent.prototype.getLanguage = function() {
  return /** @type {!proto.mktservice.ELanguage} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {!proto.mktservice.ELanguage} value */
proto.mktservice.OrganizationEvent.prototype.setLanguage = function(value) {
  jspb.Message.setProto3EnumField(this, 7, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.OrganizationEvents = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mktservice.OrganizationEvents.repeatedFields_, null);
};
goog.inherits(proto.mktservice.OrganizationEvents, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.OrganizationEvents.displayName = 'proto.mktservice.OrganizationEvents';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mktservice.OrganizationEvents.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.OrganizationEvents.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.OrganizationEvents.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.OrganizationEvents} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.OrganizationEvents.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticker: jspb.Message.getFieldWithDefault(msg, 1, ""),
    language: jspb.Message.getFieldWithDefault(msg, 2, 0),
    orgeventsList: jspb.Message.toObjectList(msg.getOrgeventsList(),
    proto.mktservice.OrganizationEvent.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.OrganizationEvents}
 */
proto.mktservice.OrganizationEvents.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.OrganizationEvents;
  return proto.mktservice.OrganizationEvents.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.OrganizationEvents} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.OrganizationEvents}
 */
proto.mktservice.OrganizationEvents.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 2:
      var value = /** @type {!proto.mktservice.ELanguage} */ (reader.readEnum());
      msg.setLanguage(value);
      break;
    case 3:
      var value = new proto.mktservice.OrganizationEvent;
      reader.readMessage(value,proto.mktservice.OrganizationEvent.deserializeBinaryFromReader);
      msg.addOrgevents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.OrganizationEvents.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.OrganizationEvents.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.OrganizationEvents} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.OrganizationEvents.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLanguage();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getOrgeventsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.mktservice.OrganizationEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional string Ticker = 1;
 * @return {string}
 */
proto.mktservice.OrganizationEvents.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.OrganizationEvents.prototype.setTicker = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ELanguage Language = 2;
 * @return {!proto.mktservice.ELanguage}
 */
proto.mktservice.OrganizationEvents.prototype.getLanguage = function() {
  return /** @type {!proto.mktservice.ELanguage} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.mktservice.ELanguage} value */
proto.mktservice.OrganizationEvents.prototype.setLanguage = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * repeated OrganizationEvent OrgEvents = 3;
 * @return {!Array<!proto.mktservice.OrganizationEvent>}
 */
proto.mktservice.OrganizationEvents.prototype.getOrgeventsList = function() {
  return /** @type{!Array<!proto.mktservice.OrganizationEvent>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mktservice.OrganizationEvent, 3));
};


/** @param {!Array<!proto.mktservice.OrganizationEvent>} value */
proto.mktservice.OrganizationEvents.prototype.setOrgeventsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.mktservice.OrganizationEvent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mktservice.OrganizationEvent}
 */
proto.mktservice.OrganizationEvents.prototype.addOrgevents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.mktservice.OrganizationEvent, opt_index);
};


proto.mktservice.OrganizationEvents.prototype.clearOrgeventsList = function() {
  this.setOrgeventsList([]);
};


goog.object.extend(exports, proto.mktservice);
