/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
var common_data_common_pb = require('../common/data_common_pb.js');
goog.exportSymbol('proto.mktservice.IndexInfo', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.IndexInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mktservice.IndexInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.IndexInfo.displayName = 'proto.mktservice.IndexInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.IndexInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.IndexInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.IndexInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.IndexInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticker: jspb.Message.getFieldWithDefault(msg, 1, ""),
    marketcode: jspb.Message.getFieldWithDefault(msg, 2, 0),
    session: jspb.Message.getFieldWithDefault(msg, 3, 0),
    indexvalue: (f = msg.getIndexvalue()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    changedindexvalue: (f = msg.getChangedindexvalue()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    changedindexpercentage: (f = msg.getChangedindexpercentage()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    previousindexvalue: (f = msg.getPreviousindexvalue()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    indexcolor: jspb.Message.getFieldWithDefault(msg, 14, 0),
    totaltrades: (f = msg.getTotaltrades()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalsharestraded: (f = msg.getTotalsharestraded()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalvaluestraded: (f = msg.getTotalvaluestraded()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalsharestraded4mt: (f = msg.getTotalsharestraded4mt()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalvaluestraded4mt: (f = msg.getTotalvaluestraded4mt()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalsharestraded4pt: (f = msg.getTotalsharestraded4pt()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalvaluestraded4pt: (f = msg.getTotalvaluestraded4pt()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    upvolume: (f = msg.getUpvolume()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    downvolume: (f = msg.getDownvolume()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    nochangevolume: (f = msg.getNochangevolume()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    advances: (f = msg.getAdvances()) && google_protobuf_wrappers_pb.Int32Value.toObject(includeInstance, f),
    declines: (f = msg.getDeclines()) && google_protobuf_wrappers_pb.Int32Value.toObject(includeInstance, f),
    nochange: (f = msg.getNochange()) && google_protobuf_wrappers_pb.Int32Value.toObject(includeInstance, f),
    totalsharestraded4foreignbuy: (f = msg.getTotalsharestraded4foreignbuy()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalsharestraded4foreignsell: (f = msg.getTotalsharestraded4foreignsell()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalvaluestraded4foreignbuy: (f = msg.getTotalvaluestraded4foreignbuy()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalvaluestraded4foreignsell: (f = msg.getTotalvaluestraded4foreignsell()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalvaluestraded4foreign: (f = msg.getTotalvaluestraded4foreign()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    open: (f = msg.getOpen()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    highest: (f = msg.getHighest()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    lowest: (f = msg.getLowest()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    closed: (f = msg.getClosed()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    opencolor: jspb.Message.getFieldWithDefault(msg, 61, 0),
    highestcolor: jspb.Message.getFieldWithDefault(msg, 62, 0),
    lowestcolor: jspb.Message.getFieldWithDefault(msg, 63, 0),
    closedcolor: jspb.Message.getFieldWithDefault(msg, 64, 0),
    time: (f = msg.getTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.IndexInfo}
 */
proto.mktservice.IndexInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.IndexInfo;
  return proto.mktservice.IndexInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.IndexInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.IndexInfo}
 */
proto.mktservice.IndexInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 2:
      var value = /** @type {!proto.mktservice.EMarketCode} */ (reader.readEnum());
      msg.setMarketcode(value);
      break;
    case 3:
      var value = /** @type {!proto.mktservice.ETradingSession} */ (reader.readEnum());
      msg.setSession(value);
      break;
    case 10:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setIndexvalue(value);
      break;
    case 11:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setChangedindexvalue(value);
      break;
    case 12:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setChangedindexpercentage(value);
      break;
    case 13:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setPreviousindexvalue(value);
      break;
    case 14:
      var value = /** @type {!proto.mktservice.EMarketColorCode} */ (reader.readEnum());
      msg.setIndexcolor(value);
      break;
    case 20:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotaltrades(value);
      break;
    case 21:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalsharestraded(value);
      break;
    case 22:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalvaluestraded(value);
      break;
    case 24:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalsharestraded4mt(value);
      break;
    case 25:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalvaluestraded4mt(value);
      break;
    case 26:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalsharestraded4pt(value);
      break;
    case 27:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalvaluestraded4pt(value);
      break;
    case 30:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setUpvolume(value);
      break;
    case 31:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setDownvolume(value);
      break;
    case 32:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setNochangevolume(value);
      break;
    case 33:
      var value = new google_protobuf_wrappers_pb.Int32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int32Value.deserializeBinaryFromReader);
      msg.setAdvances(value);
      break;
    case 34:
      var value = new google_protobuf_wrappers_pb.Int32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int32Value.deserializeBinaryFromReader);
      msg.setDeclines(value);
      break;
    case 35:
      var value = new google_protobuf_wrappers_pb.Int32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int32Value.deserializeBinaryFromReader);
      msg.setNochange(value);
      break;
    case 40:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalsharestraded4foreignbuy(value);
      break;
    case 41:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalsharestraded4foreignsell(value);
      break;
    case 42:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalvaluestraded4foreignbuy(value);
      break;
    case 43:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalvaluestraded4foreignsell(value);
      break;
    case 44:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalvaluestraded4foreign(value);
      break;
    case 50:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setOpen(value);
      break;
    case 51:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setHighest(value);
      break;
    case 52:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setLowest(value);
      break;
    case 53:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setClosed(value);
      break;
    case 61:
      var value = /** @type {!proto.mktservice.EMarketColorCode} */ (reader.readEnum());
      msg.setOpencolor(value);
      break;
    case 62:
      var value = /** @type {!proto.mktservice.EMarketColorCode} */ (reader.readEnum());
      msg.setHighestcolor(value);
      break;
    case 63:
      var value = /** @type {!proto.mktservice.EMarketColorCode} */ (reader.readEnum());
      msg.setLowestcolor(value);
      break;
    case 64:
      var value = /** @type {!proto.mktservice.EMarketColorCode} */ (reader.readEnum());
      msg.setClosedcolor(value);
      break;
    case 99:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.IndexInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.IndexInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.IndexInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.IndexInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMarketcode();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getSession();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getIndexvalue();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getChangedindexvalue();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getChangedindexpercentage();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getPreviousindexvalue();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getIndexcolor();
  if (f !== 0.0) {
    writer.writeEnum(
      14,
      f
    );
  }
  f = message.getTotaltrades();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalsharestraded();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalvaluestraded();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalsharestraded4mt();
  if (f != null) {
    writer.writeMessage(
      24,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalvaluestraded4mt();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalsharestraded4pt();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalvaluestraded4pt();
  if (f != null) {
    writer.writeMessage(
      27,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getUpvolume();
  if (f != null) {
    writer.writeMessage(
      30,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getDownvolume();
  if (f != null) {
    writer.writeMessage(
      31,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getNochangevolume();
  if (f != null) {
    writer.writeMessage(
      32,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getAdvances();
  if (f != null) {
    writer.writeMessage(
      33,
      f,
      google_protobuf_wrappers_pb.Int32Value.serializeBinaryToWriter
    );
  }
  f = message.getDeclines();
  if (f != null) {
    writer.writeMessage(
      34,
      f,
      google_protobuf_wrappers_pb.Int32Value.serializeBinaryToWriter
    );
  }
  f = message.getNochange();
  if (f != null) {
    writer.writeMessage(
      35,
      f,
      google_protobuf_wrappers_pb.Int32Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalsharestraded4foreignbuy();
  if (f != null) {
    writer.writeMessage(
      40,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalsharestraded4foreignsell();
  if (f != null) {
    writer.writeMessage(
      41,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalvaluestraded4foreignbuy();
  if (f != null) {
    writer.writeMessage(
      42,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalvaluestraded4foreignsell();
  if (f != null) {
    writer.writeMessage(
      43,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalvaluestraded4foreign();
  if (f != null) {
    writer.writeMessage(
      44,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getOpen();
  if (f != null) {
    writer.writeMessage(
      50,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getHighest();
  if (f != null) {
    writer.writeMessage(
      51,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getLowest();
  if (f != null) {
    writer.writeMessage(
      52,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getClosed();
  if (f != null) {
    writer.writeMessage(
      53,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getOpencolor();
  if (f !== 0.0) {
    writer.writeEnum(
      61,
      f
    );
  }
  f = message.getHighestcolor();
  if (f !== 0.0) {
    writer.writeEnum(
      62,
      f
    );
  }
  f = message.getLowestcolor();
  if (f !== 0.0) {
    writer.writeEnum(
      63,
      f
    );
  }
  f = message.getClosedcolor();
  if (f !== 0.0) {
    writer.writeEnum(
      64,
      f
    );
  }
  f = message.getTime();
  if (f != null) {
    writer.writeMessage(
      99,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string Ticker = 1;
 * @return {string}
 */
proto.mktservice.IndexInfo.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.IndexInfo.prototype.setTicker = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional EMarketCode MarketCode = 2;
 * @return {!proto.mktservice.EMarketCode}
 */
proto.mktservice.IndexInfo.prototype.getMarketcode = function() {
  return /** @type {!proto.mktservice.EMarketCode} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.mktservice.EMarketCode} value */
proto.mktservice.IndexInfo.prototype.setMarketcode = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional ETradingSession Session = 3;
 * @return {!proto.mktservice.ETradingSession}
 */
proto.mktservice.IndexInfo.prototype.getSession = function() {
  return /** @type {!proto.mktservice.ETradingSession} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.mktservice.ETradingSession} value */
proto.mktservice.IndexInfo.prototype.setSession = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.DoubleValue IndexValue = 10;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.IndexInfo.prototype.getIndexvalue = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 10));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.IndexInfo.prototype.setIndexvalue = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.mktservice.IndexInfo.prototype.clearIndexvalue = function() {
  this.setIndexvalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasIndexvalue = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional google.protobuf.DoubleValue ChangedIndexValue = 11;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.IndexInfo.prototype.getChangedindexvalue = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 11));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.IndexInfo.prototype.setChangedindexvalue = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.mktservice.IndexInfo.prototype.clearChangedindexvalue = function() {
  this.setChangedindexvalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasChangedindexvalue = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional google.protobuf.DoubleValue ChangedIndexPercentage = 12;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.IndexInfo.prototype.getChangedindexpercentage = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 12));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.IndexInfo.prototype.setChangedindexpercentage = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.mktservice.IndexInfo.prototype.clearChangedindexpercentage = function() {
  this.setChangedindexpercentage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasChangedindexpercentage = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional google.protobuf.DoubleValue PreviousIndexValue = 13;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.IndexInfo.prototype.getPreviousindexvalue = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 13));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.IndexInfo.prototype.setPreviousindexvalue = function(value) {
  jspb.Message.setWrapperField(this, 13, value);
};


proto.mktservice.IndexInfo.prototype.clearPreviousindexvalue = function() {
  this.setPreviousindexvalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasPreviousindexvalue = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional EMarketColorCode IndexColor = 14;
 * @return {!proto.mktservice.EMarketColorCode}
 */
proto.mktservice.IndexInfo.prototype.getIndexcolor = function() {
  return /** @type {!proto.mktservice.EMarketColorCode} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {!proto.mktservice.EMarketColorCode} value */
proto.mktservice.IndexInfo.prototype.setIndexcolor = function(value) {
  jspb.Message.setProto3EnumField(this, 14, value);
};


/**
 * optional google.protobuf.Int64Value TotalTrades = 20;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotaltrades = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 20));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotaltrades = function(value) {
  jspb.Message.setWrapperField(this, 20, value);
};


proto.mktservice.IndexInfo.prototype.clearTotaltrades = function() {
  this.setTotaltrades(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotaltrades = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional google.protobuf.Int64Value TotalSharesTraded = 21;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotalsharestraded = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 21));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotalsharestraded = function(value) {
  jspb.Message.setWrapperField(this, 21, value);
};


proto.mktservice.IndexInfo.prototype.clearTotalsharestraded = function() {
  this.setTotalsharestraded(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotalsharestraded = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional google.protobuf.Int64Value TotalValuesTraded = 22;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotalvaluestraded = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 22));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotalvaluestraded = function(value) {
  jspb.Message.setWrapperField(this, 22, value);
};


proto.mktservice.IndexInfo.prototype.clearTotalvaluestraded = function() {
  this.setTotalvaluestraded(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotalvaluestraded = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional google.protobuf.Int64Value TotalSharesTraded4MT = 24;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotalsharestraded4mt = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 24));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotalsharestraded4mt = function(value) {
  jspb.Message.setWrapperField(this, 24, value);
};


proto.mktservice.IndexInfo.prototype.clearTotalsharestraded4mt = function() {
  this.setTotalsharestraded4mt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotalsharestraded4mt = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional google.protobuf.Int64Value TotalValuesTraded4MT = 25;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotalvaluestraded4mt = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 25));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotalvaluestraded4mt = function(value) {
  jspb.Message.setWrapperField(this, 25, value);
};


proto.mktservice.IndexInfo.prototype.clearTotalvaluestraded4mt = function() {
  this.setTotalvaluestraded4mt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotalvaluestraded4mt = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional google.protobuf.Int64Value TotalSharesTraded4PT = 26;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotalsharestraded4pt = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 26));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotalsharestraded4pt = function(value) {
  jspb.Message.setWrapperField(this, 26, value);
};


proto.mktservice.IndexInfo.prototype.clearTotalsharestraded4pt = function() {
  this.setTotalsharestraded4pt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotalsharestraded4pt = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional google.protobuf.Int64Value TotalValuesTraded4PT = 27;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotalvaluestraded4pt = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 27));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotalvaluestraded4pt = function(value) {
  jspb.Message.setWrapperField(this, 27, value);
};


proto.mktservice.IndexInfo.prototype.clearTotalvaluestraded4pt = function() {
  this.setTotalvaluestraded4pt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotalvaluestraded4pt = function() {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * optional google.protobuf.Int64Value UpVolume = 30;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getUpvolume = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 30));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setUpvolume = function(value) {
  jspb.Message.setWrapperField(this, 30, value);
};


proto.mktservice.IndexInfo.prototype.clearUpvolume = function() {
  this.setUpvolume(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasUpvolume = function() {
  return jspb.Message.getField(this, 30) != null;
};


/**
 * optional google.protobuf.Int64Value DownVolume = 31;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getDownvolume = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 31));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setDownvolume = function(value) {
  jspb.Message.setWrapperField(this, 31, value);
};


proto.mktservice.IndexInfo.prototype.clearDownvolume = function() {
  this.setDownvolume(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasDownvolume = function() {
  return jspb.Message.getField(this, 31) != null;
};


/**
 * optional google.protobuf.Int64Value NoChangeVolume = 32;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getNochangevolume = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 32));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setNochangevolume = function(value) {
  jspb.Message.setWrapperField(this, 32, value);
};


proto.mktservice.IndexInfo.prototype.clearNochangevolume = function() {
  this.setNochangevolume(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasNochangevolume = function() {
  return jspb.Message.getField(this, 32) != null;
};


/**
 * optional google.protobuf.Int32Value Advances = 33;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.mktservice.IndexInfo.prototype.getAdvances = function() {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int32Value, 33));
};


/** @param {?proto.google.protobuf.Int32Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setAdvances = function(value) {
  jspb.Message.setWrapperField(this, 33, value);
};


proto.mktservice.IndexInfo.prototype.clearAdvances = function() {
  this.setAdvances(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasAdvances = function() {
  return jspb.Message.getField(this, 33) != null;
};


/**
 * optional google.protobuf.Int32Value Declines = 34;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.mktservice.IndexInfo.prototype.getDeclines = function() {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int32Value, 34));
};


/** @param {?proto.google.protobuf.Int32Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setDeclines = function(value) {
  jspb.Message.setWrapperField(this, 34, value);
};


proto.mktservice.IndexInfo.prototype.clearDeclines = function() {
  this.setDeclines(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasDeclines = function() {
  return jspb.Message.getField(this, 34) != null;
};


/**
 * optional google.protobuf.Int32Value NoChange = 35;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.mktservice.IndexInfo.prototype.getNochange = function() {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int32Value, 35));
};


/** @param {?proto.google.protobuf.Int32Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setNochange = function(value) {
  jspb.Message.setWrapperField(this, 35, value);
};


proto.mktservice.IndexInfo.prototype.clearNochange = function() {
  this.setNochange(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasNochange = function() {
  return jspb.Message.getField(this, 35) != null;
};


/**
 * optional google.protobuf.Int64Value TotalSharesTraded4ForeignBuy = 40;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotalsharestraded4foreignbuy = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 40));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotalsharestraded4foreignbuy = function(value) {
  jspb.Message.setWrapperField(this, 40, value);
};


proto.mktservice.IndexInfo.prototype.clearTotalsharestraded4foreignbuy = function() {
  this.setTotalsharestraded4foreignbuy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotalsharestraded4foreignbuy = function() {
  return jspb.Message.getField(this, 40) != null;
};


/**
 * optional google.protobuf.Int64Value TotalSharesTraded4ForeignSell = 41;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotalsharestraded4foreignsell = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 41));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotalsharestraded4foreignsell = function(value) {
  jspb.Message.setWrapperField(this, 41, value);
};


proto.mktservice.IndexInfo.prototype.clearTotalsharestraded4foreignsell = function() {
  this.setTotalsharestraded4foreignsell(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotalsharestraded4foreignsell = function() {
  return jspb.Message.getField(this, 41) != null;
};


/**
 * optional google.protobuf.Int64Value TotalValuesTraded4ForeignBuy = 42;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotalvaluestraded4foreignbuy = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 42));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotalvaluestraded4foreignbuy = function(value) {
  jspb.Message.setWrapperField(this, 42, value);
};


proto.mktservice.IndexInfo.prototype.clearTotalvaluestraded4foreignbuy = function() {
  this.setTotalvaluestraded4foreignbuy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotalvaluestraded4foreignbuy = function() {
  return jspb.Message.getField(this, 42) != null;
};


/**
 * optional google.protobuf.Int64Value TotalValuesTraded4ForeignSell = 43;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotalvaluestraded4foreignsell = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 43));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotalvaluestraded4foreignsell = function(value) {
  jspb.Message.setWrapperField(this, 43, value);
};


proto.mktservice.IndexInfo.prototype.clearTotalvaluestraded4foreignsell = function() {
  this.setTotalvaluestraded4foreignsell(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotalvaluestraded4foreignsell = function() {
  return jspb.Message.getField(this, 43) != null;
};


/**
 * optional google.protobuf.Int64Value TotalValuesTraded4Foreign = 44;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.IndexInfo.prototype.getTotalvaluestraded4foreign = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 44));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.IndexInfo.prototype.setTotalvaluestraded4foreign = function(value) {
  jspb.Message.setWrapperField(this, 44, value);
};


proto.mktservice.IndexInfo.prototype.clearTotalvaluestraded4foreign = function() {
  this.setTotalvaluestraded4foreign(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTotalvaluestraded4foreign = function() {
  return jspb.Message.getField(this, 44) != null;
};


/**
 * optional google.protobuf.DoubleValue Open = 50;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.IndexInfo.prototype.getOpen = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 50));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.IndexInfo.prototype.setOpen = function(value) {
  jspb.Message.setWrapperField(this, 50, value);
};


proto.mktservice.IndexInfo.prototype.clearOpen = function() {
  this.setOpen(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasOpen = function() {
  return jspb.Message.getField(this, 50) != null;
};


/**
 * optional google.protobuf.DoubleValue Highest = 51;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.IndexInfo.prototype.getHighest = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 51));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.IndexInfo.prototype.setHighest = function(value) {
  jspb.Message.setWrapperField(this, 51, value);
};


proto.mktservice.IndexInfo.prototype.clearHighest = function() {
  this.setHighest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasHighest = function() {
  return jspb.Message.getField(this, 51) != null;
};


/**
 * optional google.protobuf.DoubleValue Lowest = 52;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.IndexInfo.prototype.getLowest = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 52));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.IndexInfo.prototype.setLowest = function(value) {
  jspb.Message.setWrapperField(this, 52, value);
};


proto.mktservice.IndexInfo.prototype.clearLowest = function() {
  this.setLowest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasLowest = function() {
  return jspb.Message.getField(this, 52) != null;
};


/**
 * optional google.protobuf.DoubleValue Closed = 53;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.IndexInfo.prototype.getClosed = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 53));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.IndexInfo.prototype.setClosed = function(value) {
  jspb.Message.setWrapperField(this, 53, value);
};


proto.mktservice.IndexInfo.prototype.clearClosed = function() {
  this.setClosed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasClosed = function() {
  return jspb.Message.getField(this, 53) != null;
};


/**
 * optional EMarketColorCode OpenColor = 61;
 * @return {!proto.mktservice.EMarketColorCode}
 */
proto.mktservice.IndexInfo.prototype.getOpencolor = function() {
  return /** @type {!proto.mktservice.EMarketColorCode} */ (jspb.Message.getFieldWithDefault(this, 61, 0));
};


/** @param {!proto.mktservice.EMarketColorCode} value */
proto.mktservice.IndexInfo.prototype.setOpencolor = function(value) {
  jspb.Message.setProto3EnumField(this, 61, value);
};


/**
 * optional EMarketColorCode HighestColor = 62;
 * @return {!proto.mktservice.EMarketColorCode}
 */
proto.mktservice.IndexInfo.prototype.getHighestcolor = function() {
  return /** @type {!proto.mktservice.EMarketColorCode} */ (jspb.Message.getFieldWithDefault(this, 62, 0));
};


/** @param {!proto.mktservice.EMarketColorCode} value */
proto.mktservice.IndexInfo.prototype.setHighestcolor = function(value) {
  jspb.Message.setProto3EnumField(this, 62, value);
};


/**
 * optional EMarketColorCode LowestColor = 63;
 * @return {!proto.mktservice.EMarketColorCode}
 */
proto.mktservice.IndexInfo.prototype.getLowestcolor = function() {
  return /** @type {!proto.mktservice.EMarketColorCode} */ (jspb.Message.getFieldWithDefault(this, 63, 0));
};


/** @param {!proto.mktservice.EMarketColorCode} value */
proto.mktservice.IndexInfo.prototype.setLowestcolor = function(value) {
  jspb.Message.setProto3EnumField(this, 63, value);
};


/**
 * optional EMarketColorCode ClosedColor = 64;
 * @return {!proto.mktservice.EMarketColorCode}
 */
proto.mktservice.IndexInfo.prototype.getClosedcolor = function() {
  return /** @type {!proto.mktservice.EMarketColorCode} */ (jspb.Message.getFieldWithDefault(this, 64, 0));
};


/** @param {!proto.mktservice.EMarketColorCode} value */
proto.mktservice.IndexInfo.prototype.setClosedcolor = function(value) {
  jspb.Message.setProto3EnumField(this, 64, value);
};


/**
 * optional google.protobuf.Timestamp Time = 99;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.mktservice.IndexInfo.prototype.getTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 99));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.mktservice.IndexInfo.prototype.setTime = function(value) {
  jspb.Message.setWrapperField(this, 99, value);
};


proto.mktservice.IndexInfo.prototype.clearTime = function() {
  this.setTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.IndexInfo.prototype.hasTime = function() {
  return jspb.Message.getField(this, 99) != null;
};


goog.object.extend(exports, proto.mktservice);
