/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
var common_data_common_pb = require('../common/data_common_pb.js');
goog.exportSymbol('proto.mktservice.StatMarketDistribution', null, global);
goog.exportSymbol('proto.mktservice.StatMarketDistributionMarketCap', null, global);
goog.exportSymbol('proto.mktservice.StatMarketDistributionSummary', null, global);
goog.exportSymbol('proto.mktservice.StatMarketDistributionValue', null, global);
goog.exportSymbol('proto.mktservice.StatMarketDistributionVolume', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.StatMarketDistributionMarketCap = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mktservice.StatMarketDistributionMarketCap, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.StatMarketDistributionMarketCap.displayName = 'proto.mktservice.StatMarketDistributionMarketCap';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.StatMarketDistributionMarketCap.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.StatMarketDistributionMarketCap} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketDistributionMarketCap.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticker: jspb.Message.getFieldWithDefault(msg, 1, ""),
    marketcap: (f = msg.getMarketcap()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    lastsalecolor: jspb.Message.getFieldWithDefault(msg, 9, 0),
    lastprice: (f = msg.getLastprice()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    changedpercentage: (f = msg.getChangedpercentage()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    changedvalue: (f = msg.getChangedvalue()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.StatMarketDistributionMarketCap}
 */
proto.mktservice.StatMarketDistributionMarketCap.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.StatMarketDistributionMarketCap;
  return proto.mktservice.StatMarketDistributionMarketCap.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.StatMarketDistributionMarketCap} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.StatMarketDistributionMarketCap}
 */
proto.mktservice.StatMarketDistributionMarketCap.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setMarketcap(value);
      break;
    case 9:
      var value = /** @type {!proto.mktservice.EMarketColorCode} */ (reader.readEnum());
      msg.setLastsalecolor(value);
      break;
    case 20:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setLastprice(value);
      break;
    case 21:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setChangedpercentage(value);
      break;
    case 22:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setChangedvalue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.StatMarketDistributionMarketCap.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.StatMarketDistributionMarketCap} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketDistributionMarketCap.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMarketcap();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getLastsalecolor();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getLastprice();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getChangedpercentage();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getChangedvalue();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string Ticker = 1;
 * @return {string}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.StatMarketDistributionMarketCap.prototype.setTicker = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.DoubleValue MarketCap = 2;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.getMarketcap = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 2));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionMarketCap.prototype.setMarketcap = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.mktservice.StatMarketDistributionMarketCap.prototype.clearMarketcap = function() {
  this.setMarketcap(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.hasMarketcap = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional EMarketColorCode LastSaleColor = 9;
 * @return {!proto.mktservice.EMarketColorCode}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.getLastsalecolor = function() {
  return /** @type {!proto.mktservice.EMarketColorCode} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {!proto.mktservice.EMarketColorCode} value */
proto.mktservice.StatMarketDistributionMarketCap.prototype.setLastsalecolor = function(value) {
  jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional google.protobuf.DoubleValue LastPrice = 20;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.getLastprice = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 20));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionMarketCap.prototype.setLastprice = function(value) {
  jspb.Message.setWrapperField(this, 20, value);
};


proto.mktservice.StatMarketDistributionMarketCap.prototype.clearLastprice = function() {
  this.setLastprice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.hasLastprice = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional google.protobuf.DoubleValue ChangedPercentage = 21;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.getChangedpercentage = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 21));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionMarketCap.prototype.setChangedpercentage = function(value) {
  jspb.Message.setWrapperField(this, 21, value);
};


proto.mktservice.StatMarketDistributionMarketCap.prototype.clearChangedpercentage = function() {
  this.setChangedpercentage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.hasChangedpercentage = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional google.protobuf.DoubleValue ChangedValue = 22;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.getChangedvalue = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 22));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionMarketCap.prototype.setChangedvalue = function(value) {
  jspb.Message.setWrapperField(this, 22, value);
};


proto.mktservice.StatMarketDistributionMarketCap.prototype.clearChangedvalue = function() {
  this.setChangedvalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionMarketCap.prototype.hasChangedvalue = function() {
  return jspb.Message.getField(this, 22) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.StatMarketDistributionVolume = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mktservice.StatMarketDistributionVolume, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.StatMarketDistributionVolume.displayName = 'proto.mktservice.StatMarketDistributionVolume';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.StatMarketDistributionVolume.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.StatMarketDistributionVolume} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketDistributionVolume.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticker: jspb.Message.getFieldWithDefault(msg, 1, ""),
    totalvolume: (f = msg.getTotalvolume()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    totalvolumetradedmt: (f = msg.getTotalvolumetradedmt()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    totalvolumetradedpt: (f = msg.getTotalvolumetradedpt()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    lastsalecolor: jspb.Message.getFieldWithDefault(msg, 9, 0),
    lastprice: (f = msg.getLastprice()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    changedpercentage: (f = msg.getChangedpercentage()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    changedvalue: (f = msg.getChangedvalue()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.StatMarketDistributionVolume}
 */
proto.mktservice.StatMarketDistributionVolume.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.StatMarketDistributionVolume;
  return proto.mktservice.StatMarketDistributionVolume.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.StatMarketDistributionVolume} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.StatMarketDistributionVolume}
 */
proto.mktservice.StatMarketDistributionVolume.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvolume(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvolumetradedmt(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvolumetradedpt(value);
      break;
    case 9:
      var value = /** @type {!proto.mktservice.EMarketColorCode} */ (reader.readEnum());
      msg.setLastsalecolor(value);
      break;
    case 20:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setLastprice(value);
      break;
    case 21:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setChangedpercentage(value);
      break;
    case 22:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setChangedvalue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.StatMarketDistributionVolume.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.StatMarketDistributionVolume} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketDistributionVolume.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTotalvolume();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTotalvolumetradedmt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTotalvolumetradedpt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getLastsalecolor();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getLastprice();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getChangedpercentage();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getChangedvalue();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string Ticker = 1;
 * @return {string}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.StatMarketDistributionVolume.prototype.setTicker = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.DoubleValue TotalVolume = 2;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.getTotalvolume = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 2));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionVolume.prototype.setTotalvolume = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.mktservice.StatMarketDistributionVolume.prototype.clearTotalvolume = function() {
  this.setTotalvolume(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.hasTotalvolume = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.DoubleValue TotalVolumeTradedMT = 3;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.getTotalvolumetradedmt = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 3));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionVolume.prototype.setTotalvolumetradedmt = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.mktservice.StatMarketDistributionVolume.prototype.clearTotalvolumetradedmt = function() {
  this.setTotalvolumetradedmt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.hasTotalvolumetradedmt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.DoubleValue TotalVolumeTradedPT = 4;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.getTotalvolumetradedpt = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 4));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionVolume.prototype.setTotalvolumetradedpt = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.mktservice.StatMarketDistributionVolume.prototype.clearTotalvolumetradedpt = function() {
  this.setTotalvolumetradedpt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.hasTotalvolumetradedpt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional EMarketColorCode LastSaleColor = 9;
 * @return {!proto.mktservice.EMarketColorCode}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.getLastsalecolor = function() {
  return /** @type {!proto.mktservice.EMarketColorCode} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {!proto.mktservice.EMarketColorCode} value */
proto.mktservice.StatMarketDistributionVolume.prototype.setLastsalecolor = function(value) {
  jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional google.protobuf.DoubleValue LastPrice = 20;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.getLastprice = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 20));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionVolume.prototype.setLastprice = function(value) {
  jspb.Message.setWrapperField(this, 20, value);
};


proto.mktservice.StatMarketDistributionVolume.prototype.clearLastprice = function() {
  this.setLastprice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.hasLastprice = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional google.protobuf.DoubleValue ChangedPercentage = 21;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.getChangedpercentage = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 21));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionVolume.prototype.setChangedpercentage = function(value) {
  jspb.Message.setWrapperField(this, 21, value);
};


proto.mktservice.StatMarketDistributionVolume.prototype.clearChangedpercentage = function() {
  this.setChangedpercentage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.hasChangedpercentage = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional google.protobuf.DoubleValue ChangedValue = 22;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.getChangedvalue = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 22));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionVolume.prototype.setChangedvalue = function(value) {
  jspb.Message.setWrapperField(this, 22, value);
};


proto.mktservice.StatMarketDistributionVolume.prototype.clearChangedvalue = function() {
  this.setChangedvalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionVolume.prototype.hasChangedvalue = function() {
  return jspb.Message.getField(this, 22) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.StatMarketDistributionValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mktservice.StatMarketDistributionValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.StatMarketDistributionValue.displayName = 'proto.mktservice.StatMarketDistributionValue';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.StatMarketDistributionValue.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.StatMarketDistributionValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.StatMarketDistributionValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketDistributionValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticker: jspb.Message.getFieldWithDefault(msg, 1, ""),
    totalvaluestraded: (f = msg.getTotalvaluestraded()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    totalvaluestradedmt: (f = msg.getTotalvaluestradedmt()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    totalvaluestradedpt: (f = msg.getTotalvaluestradedpt()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    lastsalecolor: jspb.Message.getFieldWithDefault(msg, 9, 0),
    lastprice: (f = msg.getLastprice()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    changedpercentage: (f = msg.getChangedpercentage()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    changedvalue: (f = msg.getChangedvalue()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.StatMarketDistributionValue}
 */
proto.mktservice.StatMarketDistributionValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.StatMarketDistributionValue;
  return proto.mktservice.StatMarketDistributionValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.StatMarketDistributionValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.StatMarketDistributionValue}
 */
proto.mktservice.StatMarketDistributionValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvaluestraded(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvaluestradedmt(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvaluestradedpt(value);
      break;
    case 9:
      var value = /** @type {!proto.mktservice.EMarketColorCode} */ (reader.readEnum());
      msg.setLastsalecolor(value);
      break;
    case 20:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setLastprice(value);
      break;
    case 21:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setChangedpercentage(value);
      break;
    case 22:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setChangedvalue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.StatMarketDistributionValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.StatMarketDistributionValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.StatMarketDistributionValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketDistributionValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTotalvaluestraded();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTotalvaluestradedmt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTotalvaluestradedpt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getLastsalecolor();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getLastprice();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getChangedpercentage();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getChangedvalue();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string Ticker = 1;
 * @return {string}
 */
proto.mktservice.StatMarketDistributionValue.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.StatMarketDistributionValue.prototype.setTicker = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.DoubleValue TotalValuesTraded = 2;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionValue.prototype.getTotalvaluestraded = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 2));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionValue.prototype.setTotalvaluestraded = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.mktservice.StatMarketDistributionValue.prototype.clearTotalvaluestraded = function() {
  this.setTotalvaluestraded(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionValue.prototype.hasTotalvaluestraded = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.DoubleValue TotalValuesTradedMT = 3;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionValue.prototype.getTotalvaluestradedmt = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 3));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionValue.prototype.setTotalvaluestradedmt = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.mktservice.StatMarketDistributionValue.prototype.clearTotalvaluestradedmt = function() {
  this.setTotalvaluestradedmt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionValue.prototype.hasTotalvaluestradedmt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.DoubleValue TotalValuesTradedPT = 4;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionValue.prototype.getTotalvaluestradedpt = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 4));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionValue.prototype.setTotalvaluestradedpt = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.mktservice.StatMarketDistributionValue.prototype.clearTotalvaluestradedpt = function() {
  this.setTotalvaluestradedpt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionValue.prototype.hasTotalvaluestradedpt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional EMarketColorCode LastSaleColor = 9;
 * @return {!proto.mktservice.EMarketColorCode}
 */
proto.mktservice.StatMarketDistributionValue.prototype.getLastsalecolor = function() {
  return /** @type {!proto.mktservice.EMarketColorCode} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {!proto.mktservice.EMarketColorCode} value */
proto.mktservice.StatMarketDistributionValue.prototype.setLastsalecolor = function(value) {
  jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional google.protobuf.DoubleValue LastPrice = 20;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionValue.prototype.getLastprice = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 20));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionValue.prototype.setLastprice = function(value) {
  jspb.Message.setWrapperField(this, 20, value);
};


proto.mktservice.StatMarketDistributionValue.prototype.clearLastprice = function() {
  this.setLastprice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionValue.prototype.hasLastprice = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional google.protobuf.DoubleValue ChangedPercentage = 21;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionValue.prototype.getChangedpercentage = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 21));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionValue.prototype.setChangedpercentage = function(value) {
  jspb.Message.setWrapperField(this, 21, value);
};


proto.mktservice.StatMarketDistributionValue.prototype.clearChangedpercentage = function() {
  this.setChangedpercentage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionValue.prototype.hasChangedpercentage = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional google.protobuf.DoubleValue ChangedValue = 22;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionValue.prototype.getChangedvalue = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 22));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionValue.prototype.setChangedvalue = function(value) {
  jspb.Message.setWrapperField(this, 22, value);
};


proto.mktservice.StatMarketDistributionValue.prototype.clearChangedvalue = function() {
  this.setChangedvalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionValue.prototype.hasChangedvalue = function() {
  return jspb.Message.getField(this, 22) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.StatMarketDistributionSummary = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mktservice.StatMarketDistributionSummary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.StatMarketDistributionSummary.displayName = 'proto.mktservice.StatMarketDistributionSummary';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.StatMarketDistributionSummary.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.StatMarketDistributionSummary} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketDistributionSummary.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticker: jspb.Message.getFieldWithDefault(msg, 1, ""),
    marketcap: (f = msg.getMarketcap()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    totalvaluestraded: (f = msg.getTotalvaluestraded()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    totalvaluestradedmt: (f = msg.getTotalvaluestradedmt()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    totalvaluestradedpt: (f = msg.getTotalvaluestradedpt()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    totalvolumetradedmt: (f = msg.getTotalvolumetradedmt()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    totalvolumetradedpt: (f = msg.getTotalvolumetradedpt()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    lastprice: (f = msg.getLastprice()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    changedpercentage: (f = msg.getChangedpercentage()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    changedvalue: (f = msg.getChangedvalue()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    totalvolume: (f = msg.getTotalvolume()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.StatMarketDistributionSummary}
 */
proto.mktservice.StatMarketDistributionSummary.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.StatMarketDistributionSummary;
  return proto.mktservice.StatMarketDistributionSummary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.StatMarketDistributionSummary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.StatMarketDistributionSummary}
 */
proto.mktservice.StatMarketDistributionSummary.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setMarketcap(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvaluestraded(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvaluestradedmt(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvaluestradedpt(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvolumetradedmt(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvolumetradedpt(value);
      break;
    case 20:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setLastprice(value);
      break;
    case 21:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setChangedpercentage(value);
      break;
    case 22:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setChangedvalue(value);
      break;
    case 23:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTotalvolume(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.StatMarketDistributionSummary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.StatMarketDistributionSummary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketDistributionSummary.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMarketcap();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTotalvaluestraded();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTotalvaluestradedmt();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTotalvaluestradedpt();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTotalvolumetradedmt();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTotalvolumetradedpt();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getLastprice();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getChangedpercentage();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getChangedvalue();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTotalvolume();
  if (f != null) {
    writer.writeMessage(
      23,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string Ticker = 1;
 * @return {string}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.StatMarketDistributionSummary.prototype.setTicker = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.DoubleValue MarketCap = 2;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.getMarketcap = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 2));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionSummary.prototype.setMarketcap = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.mktservice.StatMarketDistributionSummary.prototype.clearMarketcap = function() {
  this.setMarketcap(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.hasMarketcap = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.DoubleValue TotalValuesTraded = 3;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.getTotalvaluestraded = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 3));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionSummary.prototype.setTotalvaluestraded = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.mktservice.StatMarketDistributionSummary.prototype.clearTotalvaluestraded = function() {
  this.setTotalvaluestraded(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.hasTotalvaluestraded = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.DoubleValue TotalValuesTradedMT = 5;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.getTotalvaluestradedmt = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 5));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionSummary.prototype.setTotalvaluestradedmt = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.mktservice.StatMarketDistributionSummary.prototype.clearTotalvaluestradedmt = function() {
  this.setTotalvaluestradedmt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.hasTotalvaluestradedmt = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.DoubleValue TotalValuesTradedPT = 6;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.getTotalvaluestradedpt = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 6));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionSummary.prototype.setTotalvaluestradedpt = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.mktservice.StatMarketDistributionSummary.prototype.clearTotalvaluestradedpt = function() {
  this.setTotalvaluestradedpt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.hasTotalvaluestradedpt = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.DoubleValue TotalVolumeTradedMT = 7;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.getTotalvolumetradedmt = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 7));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionSummary.prototype.setTotalvolumetradedmt = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.mktservice.StatMarketDistributionSummary.prototype.clearTotalvolumetradedmt = function() {
  this.setTotalvolumetradedmt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.hasTotalvolumetradedmt = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.DoubleValue TotalVolumeTradedPT = 8;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.getTotalvolumetradedpt = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 8));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionSummary.prototype.setTotalvolumetradedpt = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.mktservice.StatMarketDistributionSummary.prototype.clearTotalvolumetradedpt = function() {
  this.setTotalvolumetradedpt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.hasTotalvolumetradedpt = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.DoubleValue LastPrice = 20;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.getLastprice = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 20));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionSummary.prototype.setLastprice = function(value) {
  jspb.Message.setWrapperField(this, 20, value);
};


proto.mktservice.StatMarketDistributionSummary.prototype.clearLastprice = function() {
  this.setLastprice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.hasLastprice = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional google.protobuf.DoubleValue ChangedPercentage = 21;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.getChangedpercentage = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 21));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionSummary.prototype.setChangedpercentage = function(value) {
  jspb.Message.setWrapperField(this, 21, value);
};


proto.mktservice.StatMarketDistributionSummary.prototype.clearChangedpercentage = function() {
  this.setChangedpercentage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.hasChangedpercentage = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional google.protobuf.DoubleValue ChangedValue = 22;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.getChangedvalue = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 22));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionSummary.prototype.setChangedvalue = function(value) {
  jspb.Message.setWrapperField(this, 22, value);
};


proto.mktservice.StatMarketDistributionSummary.prototype.clearChangedvalue = function() {
  this.setChangedvalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.hasChangedvalue = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional google.protobuf.DoubleValue TotalVolume = 23;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.getTotalvolume = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 23));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketDistributionSummary.prototype.setTotalvolume = function(value) {
  jspb.Message.setWrapperField(this, 23, value);
};


proto.mktservice.StatMarketDistributionSummary.prototype.clearTotalvolume = function() {
  this.setTotalvolume(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistributionSummary.prototype.hasTotalvolume = function() {
  return jspb.Message.getField(this, 23) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.StatMarketDistribution = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mktservice.StatMarketDistribution.repeatedFields_, null);
};
goog.inherits(proto.mktservice.StatMarketDistribution, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.StatMarketDistribution.displayName = 'proto.mktservice.StatMarketDistribution';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mktservice.StatMarketDistribution.repeatedFields_ = [20,22,23,24];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.StatMarketDistribution.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.StatMarketDistribution.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.StatMarketDistribution} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketDistribution.toObject = function(includeInstance, msg) {
  var f, obj = {
    date: (f = msg.getDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    basketcode: jspb.Message.getFieldWithDefault(msg, 3, ""),
    type: jspb.Message.getFieldWithDefault(msg, 4, 0),
    color: jspb.Message.getFieldWithDefault(msg, 5, 0),
    marketcapdistributionList: jspb.Message.toObjectList(msg.getMarketcapdistributionList(),
    proto.mktservice.StatMarketDistributionMarketCap.toObject, includeInstance),
    volumedistributionList: jspb.Message.toObjectList(msg.getVolumedistributionList(),
    proto.mktservice.StatMarketDistributionVolume.toObject, includeInstance),
    valuedistributionList: jspb.Message.toObjectList(msg.getValuedistributionList(),
    proto.mktservice.StatMarketDistributionValue.toObject, includeInstance),
    summarydistributionList: jspb.Message.toObjectList(msg.getSummarydistributionList(),
    proto.mktservice.StatMarketDistributionSummary.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.StatMarketDistribution}
 */
proto.mktservice.StatMarketDistribution.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.StatMarketDistribution;
  return proto.mktservice.StatMarketDistribution.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.StatMarketDistribution} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.StatMarketDistribution}
 */
proto.mktservice.StatMarketDistribution.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDate(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBasketcode(value);
      break;
    case 4:
      var value = /** @type {!proto.mktservice.EMarketDistributionType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = /** @type {!proto.mktservice.EMarketColorCode} */ (reader.readEnum());
      msg.setColor(value);
      break;
    case 20:
      var value = new proto.mktservice.StatMarketDistributionMarketCap;
      reader.readMessage(value,proto.mktservice.StatMarketDistributionMarketCap.deserializeBinaryFromReader);
      msg.addMarketcapdistribution(value);
      break;
    case 22:
      var value = new proto.mktservice.StatMarketDistributionVolume;
      reader.readMessage(value,proto.mktservice.StatMarketDistributionVolume.deserializeBinaryFromReader);
      msg.addVolumedistribution(value);
      break;
    case 23:
      var value = new proto.mktservice.StatMarketDistributionValue;
      reader.readMessage(value,proto.mktservice.StatMarketDistributionValue.deserializeBinaryFromReader);
      msg.addValuedistribution(value);
      break;
    case 24:
      var value = new proto.mktservice.StatMarketDistributionSummary;
      reader.readMessage(value,proto.mktservice.StatMarketDistributionSummary.deserializeBinaryFromReader);
      msg.addSummarydistribution(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.StatMarketDistribution.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.StatMarketDistribution.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.StatMarketDistribution} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketDistribution.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getBasketcode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getColor();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getMarketcapdistributionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      proto.mktservice.StatMarketDistributionMarketCap.serializeBinaryToWriter
    );
  }
  f = message.getVolumedistributionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      22,
      f,
      proto.mktservice.StatMarketDistributionVolume.serializeBinaryToWriter
    );
  }
  f = message.getValuedistributionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      23,
      f,
      proto.mktservice.StatMarketDistributionValue.serializeBinaryToWriter
    );
  }
  f = message.getSummarydistributionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      24,
      f,
      proto.mktservice.StatMarketDistributionSummary.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp Date = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.mktservice.StatMarketDistribution.prototype.getDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.mktservice.StatMarketDistribution.prototype.setDate = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.mktservice.StatMarketDistribution.prototype.clearDate = function() {
  this.setDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketDistribution.prototype.hasDate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string BasketCode = 3;
 * @return {string}
 */
proto.mktservice.StatMarketDistribution.prototype.getBasketcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.mktservice.StatMarketDistribution.prototype.setBasketcode = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional EMarketDistributionType Type = 4;
 * @return {!proto.mktservice.EMarketDistributionType}
 */
proto.mktservice.StatMarketDistribution.prototype.getType = function() {
  return /** @type {!proto.mktservice.EMarketDistributionType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.mktservice.EMarketDistributionType} value */
proto.mktservice.StatMarketDistribution.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional EMarketColorCode Color = 5;
 * @return {!proto.mktservice.EMarketColorCode}
 */
proto.mktservice.StatMarketDistribution.prototype.getColor = function() {
  return /** @type {!proto.mktservice.EMarketColorCode} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.mktservice.EMarketColorCode} value */
proto.mktservice.StatMarketDistribution.prototype.setColor = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * repeated StatMarketDistributionMarketCap MarketCapDistribution = 20;
 * @return {!Array<!proto.mktservice.StatMarketDistributionMarketCap>}
 */
proto.mktservice.StatMarketDistribution.prototype.getMarketcapdistributionList = function() {
  return /** @type{!Array<!proto.mktservice.StatMarketDistributionMarketCap>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mktservice.StatMarketDistributionMarketCap, 20));
};


/** @param {!Array<!proto.mktservice.StatMarketDistributionMarketCap>} value */
proto.mktservice.StatMarketDistribution.prototype.setMarketcapdistributionList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.mktservice.StatMarketDistributionMarketCap=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mktservice.StatMarketDistributionMarketCap}
 */
proto.mktservice.StatMarketDistribution.prototype.addMarketcapdistribution = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.mktservice.StatMarketDistributionMarketCap, opt_index);
};


proto.mktservice.StatMarketDistribution.prototype.clearMarketcapdistributionList = function() {
  this.setMarketcapdistributionList([]);
};


/**
 * repeated StatMarketDistributionVolume VolumeDistribution = 22;
 * @return {!Array<!proto.mktservice.StatMarketDistributionVolume>}
 */
proto.mktservice.StatMarketDistribution.prototype.getVolumedistributionList = function() {
  return /** @type{!Array<!proto.mktservice.StatMarketDistributionVolume>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mktservice.StatMarketDistributionVolume, 22));
};


/** @param {!Array<!proto.mktservice.StatMarketDistributionVolume>} value */
proto.mktservice.StatMarketDistribution.prototype.setVolumedistributionList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 22, value);
};


/**
 * @param {!proto.mktservice.StatMarketDistributionVolume=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mktservice.StatMarketDistributionVolume}
 */
proto.mktservice.StatMarketDistribution.prototype.addVolumedistribution = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 22, opt_value, proto.mktservice.StatMarketDistributionVolume, opt_index);
};


proto.mktservice.StatMarketDistribution.prototype.clearVolumedistributionList = function() {
  this.setVolumedistributionList([]);
};


/**
 * repeated StatMarketDistributionValue ValueDistribution = 23;
 * @return {!Array<!proto.mktservice.StatMarketDistributionValue>}
 */
proto.mktservice.StatMarketDistribution.prototype.getValuedistributionList = function() {
  return /** @type{!Array<!proto.mktservice.StatMarketDistributionValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mktservice.StatMarketDistributionValue, 23));
};


/** @param {!Array<!proto.mktservice.StatMarketDistributionValue>} value */
proto.mktservice.StatMarketDistribution.prototype.setValuedistributionList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 23, value);
};


/**
 * @param {!proto.mktservice.StatMarketDistributionValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mktservice.StatMarketDistributionValue}
 */
proto.mktservice.StatMarketDistribution.prototype.addValuedistribution = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 23, opt_value, proto.mktservice.StatMarketDistributionValue, opt_index);
};


proto.mktservice.StatMarketDistribution.prototype.clearValuedistributionList = function() {
  this.setValuedistributionList([]);
};


/**
 * repeated StatMarketDistributionSummary SummaryDistribution = 24;
 * @return {!Array<!proto.mktservice.StatMarketDistributionSummary>}
 */
proto.mktservice.StatMarketDistribution.prototype.getSummarydistributionList = function() {
  return /** @type{!Array<!proto.mktservice.StatMarketDistributionSummary>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mktservice.StatMarketDistributionSummary, 24));
};


/** @param {!Array<!proto.mktservice.StatMarketDistributionSummary>} value */
proto.mktservice.StatMarketDistribution.prototype.setSummarydistributionList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 24, value);
};


/**
 * @param {!proto.mktservice.StatMarketDistributionSummary=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mktservice.StatMarketDistributionSummary}
 */
proto.mktservice.StatMarketDistribution.prototype.addSummarydistribution = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 24, opt_value, proto.mktservice.StatMarketDistributionSummary, opt_index);
};


proto.mktservice.StatMarketDistribution.prototype.clearSummarydistributionList = function() {
  this.setSummarydistributionList([]);
};


goog.object.extend(exports, proto.mktservice);
