/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
var common_data_common_pb = require('../common/data_common_pb.js');
goog.exportSymbol('proto.mktservice.ECWStatus', null, global);
goog.exportSymbol('proto.mktservice.StatTicker', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.StatTicker = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mktservice.StatTicker, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.StatTicker.displayName = 'proto.mktservice.StatTicker';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.StatTicker.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.StatTicker.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.StatTicker} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatTicker.toObject = function(includeInstance, msg) {
  var f, obj = {
    sharecode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    tickertype: jspb.Message.getFieldWithDefault(msg, 2, 0),
    cwstatus: jspb.Message.getFieldWithDefault(msg, 3, 0),
    biasprice: (f = msg.getBiasprice()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    balanceprice: (f = msg.getBalanceprice()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.StatTicker}
 */
proto.mktservice.StatTicker.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.StatTicker;
  return proto.mktservice.StatTicker.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.StatTicker} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.StatTicker}
 */
proto.mktservice.StatTicker.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSharecode(value);
      break;
    case 2:
      var value = /** @type {!proto.mktservice.ETickerType} */ (reader.readEnum());
      msg.setTickertype(value);
      break;
    case 3:
      var value = /** @type {!proto.mktservice.ECWStatus} */ (reader.readEnum());
      msg.setCwstatus(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setBiasprice(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setBalanceprice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.StatTicker.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.StatTicker.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.StatTicker} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatTicker.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSharecode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTickertype();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getCwstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getBiasprice();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getBalanceprice();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ShareCode = 1;
 * @return {string}
 */
proto.mktservice.StatTicker.prototype.getSharecode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.StatTicker.prototype.setSharecode = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ETickerType TickerType = 2;
 * @return {!proto.mktservice.ETickerType}
 */
proto.mktservice.StatTicker.prototype.getTickertype = function() {
  return /** @type {!proto.mktservice.ETickerType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.mktservice.ETickerType} value */
proto.mktservice.StatTicker.prototype.setTickertype = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional ECWStatus CWStatus = 3;
 * @return {!proto.mktservice.ECWStatus}
 */
proto.mktservice.StatTicker.prototype.getCwstatus = function() {
  return /** @type {!proto.mktservice.ECWStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.mktservice.ECWStatus} value */
proto.mktservice.StatTicker.prototype.setCwstatus = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.DoubleValue BiasPrice = 4;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatTicker.prototype.getBiasprice = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 4));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatTicker.prototype.setBiasprice = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.mktservice.StatTicker.prototype.clearBiasprice = function() {
  this.setBiasprice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatTicker.prototype.hasBiasprice = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.DoubleValue BalancePrice = 5;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatTicker.prototype.getBalanceprice = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 5));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatTicker.prototype.setBalanceprice = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.mktservice.StatTicker.prototype.clearBalanceprice = function() {
  this.setBalanceprice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatTicker.prototype.hasBalanceprice = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.mktservice.ECWStatus = {
  CW_ITM: 0,
  CW_ATM: 1,
  CW_OTP: 2
};

goog.object.extend(exports, proto.mktservice);
