/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
var common_data_common_pb = require('../common/data_common_pb.js');
goog.exportSymbol('proto.mktservice.StatMarketContributionDetail', null, global);
goog.exportSymbol('proto.mktservice.StatMarketScaleDetail', null, global);
goog.exportSymbol('proto.mktservice.StatMarketStats', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.StatMarketScaleDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mktservice.StatMarketScaleDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.StatMarketScaleDetail.displayName = 'proto.mktservice.StatMarketScaleDetail';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.StatMarketScaleDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.StatMarketScaleDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.StatMarketScaleDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketScaleDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticker: jspb.Message.getFieldWithDefault(msg, 1, ""),
    changedpercentvolumewithavg5d: (f = msg.getChangedpercentvolumewithavg5d()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    marketpercent: (f = msg.getMarketpercent()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    contrivalue: (f = msg.getContrivalue()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    contripercentage: (f = msg.getContripercentage()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    lastsalecolor: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.StatMarketScaleDetail}
 */
proto.mktservice.StatMarketScaleDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.StatMarketScaleDetail;
  return proto.mktservice.StatMarketScaleDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.StatMarketScaleDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.StatMarketScaleDetail}
 */
proto.mktservice.StatMarketScaleDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setChangedpercentvolumewithavg5d(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setMarketpercent(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setContrivalue(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setContripercentage(value);
      break;
    case 6:
      var value = /** @type {!proto.mktservice.EMarketColorCode} */ (reader.readEnum());
      msg.setLastsalecolor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.StatMarketScaleDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.StatMarketScaleDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.StatMarketScaleDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketScaleDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getChangedpercentvolumewithavg5d();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getMarketpercent();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getContrivalue();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getContripercentage();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getLastsalecolor();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional string Ticker = 1;
 * @return {string}
 */
proto.mktservice.StatMarketScaleDetail.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.StatMarketScaleDetail.prototype.setTicker = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.DoubleValue ChangedPercentVolumeWithAvg5d = 2;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketScaleDetail.prototype.getChangedpercentvolumewithavg5d = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 2));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketScaleDetail.prototype.setChangedpercentvolumewithavg5d = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.mktservice.StatMarketScaleDetail.prototype.clearChangedpercentvolumewithavg5d = function() {
  this.setChangedpercentvolumewithavg5d(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketScaleDetail.prototype.hasChangedpercentvolumewithavg5d = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.DoubleValue MarketPercent = 3;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketScaleDetail.prototype.getMarketpercent = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 3));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketScaleDetail.prototype.setMarketpercent = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.mktservice.StatMarketScaleDetail.prototype.clearMarketpercent = function() {
  this.setMarketpercent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketScaleDetail.prototype.hasMarketpercent = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.DoubleValue ContriValue = 4;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketScaleDetail.prototype.getContrivalue = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 4));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketScaleDetail.prototype.setContrivalue = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.mktservice.StatMarketScaleDetail.prototype.clearContrivalue = function() {
  this.setContrivalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketScaleDetail.prototype.hasContrivalue = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.DoubleValue ContriPercentage = 5;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketScaleDetail.prototype.getContripercentage = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 5));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketScaleDetail.prototype.setContripercentage = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.mktservice.StatMarketScaleDetail.prototype.clearContripercentage = function() {
  this.setContripercentage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketScaleDetail.prototype.hasContripercentage = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional EMarketColorCode LastSaleColor = 6;
 * @return {!proto.mktservice.EMarketColorCode}
 */
proto.mktservice.StatMarketScaleDetail.prototype.getLastsalecolor = function() {
  return /** @type {!proto.mktservice.EMarketColorCode} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {!proto.mktservice.EMarketColorCode} value */
proto.mktservice.StatMarketScaleDetail.prototype.setLastsalecolor = function(value) {
  jspb.Message.setProto3EnumField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.StatMarketContributionDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mktservice.StatMarketContributionDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.StatMarketContributionDetail.displayName = 'proto.mktservice.StatMarketContributionDetail';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.StatMarketContributionDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.StatMarketContributionDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.StatMarketContributionDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketContributionDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticker: jspb.Message.getFieldWithDefault(msg, 1, ""),
    contrivalue: (f = msg.getContrivalue()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    contripercentage: (f = msg.getContripercentage()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.StatMarketContributionDetail}
 */
proto.mktservice.StatMarketContributionDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.StatMarketContributionDetail;
  return proto.mktservice.StatMarketContributionDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.StatMarketContributionDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.StatMarketContributionDetail}
 */
proto.mktservice.StatMarketContributionDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicker(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setContrivalue(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setContripercentage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.StatMarketContributionDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.StatMarketContributionDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.StatMarketContributionDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketContributionDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicker();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContrivalue();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getContripercentage();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string Ticker = 1;
 * @return {string}
 */
proto.mktservice.StatMarketContributionDetail.prototype.getTicker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.mktservice.StatMarketContributionDetail.prototype.setTicker = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.DoubleValue ContriValue = 5;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketContributionDetail.prototype.getContrivalue = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 5));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketContributionDetail.prototype.setContrivalue = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.mktservice.StatMarketContributionDetail.prototype.clearContrivalue = function() {
  this.setContrivalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketContributionDetail.prototype.hasContrivalue = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.DoubleValue ContriPercentage = 6;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketContributionDetail.prototype.getContripercentage = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 6));
};


/** @param {?proto.google.protobuf.DoubleValue|undefined} value */
proto.mktservice.StatMarketContributionDetail.prototype.setContripercentage = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.mktservice.StatMarketContributionDetail.prototype.clearContripercentage = function() {
  this.setContripercentage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketContributionDetail.prototype.hasContripercentage = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.StatMarketStats = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mktservice.StatMarketStats.repeatedFields_, null);
};
goog.inherits(proto.mktservice.StatMarketStats, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.StatMarketStats.displayName = 'proto.mktservice.StatMarketStats';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mktservice.StatMarketStats.repeatedFields_ = [20,21];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.StatMarketStats.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.StatMarketStats.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.StatMarketStats} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketStats.toObject = function(includeInstance, msg) {
  var f, obj = {
    date: (f = msg.getDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    basketcode: jspb.Message.getFieldWithDefault(msg, 3, ""),
    type: jspb.Message.getFieldWithDefault(msg, 4, 0),
    totalfloorshares: (f = msg.getTotalfloorshares()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totaldeclineshares: (f = msg.getTotaldeclineshares()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalnochangeshares: (f = msg.getTotalnochangeshares()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totaladvanceshares: (f = msg.getTotaladvanceshares()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalceilingshares: (f = msg.getTotalceilingshares()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    contributionstatsList: jspb.Message.toObjectList(msg.getContributionstatsList(),
    proto.mktservice.StatMarketContributionDetail.toObject, includeInstance),
    scalestatsList: jspb.Message.toObjectList(msg.getScalestatsList(),
    proto.mktservice.StatMarketScaleDetail.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.StatMarketStats}
 */
proto.mktservice.StatMarketStats.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.StatMarketStats;
  return proto.mktservice.StatMarketStats.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.StatMarketStats} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.StatMarketStats}
 */
proto.mktservice.StatMarketStats.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDate(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBasketcode(value);
      break;
    case 4:
      var value = /** @type {!proto.mktservice.EMarketStatsType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalfloorshares(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotaldeclineshares(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalnochangeshares(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotaladvanceshares(value);
      break;
    case 9:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalceilingshares(value);
      break;
    case 20:
      var value = new proto.mktservice.StatMarketContributionDetail;
      reader.readMessage(value,proto.mktservice.StatMarketContributionDetail.deserializeBinaryFromReader);
      msg.addContributionstats(value);
      break;
    case 21:
      var value = new proto.mktservice.StatMarketScaleDetail;
      reader.readMessage(value,proto.mktservice.StatMarketScaleDetail.deserializeBinaryFromReader);
      msg.addScalestats(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.StatMarketStats.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.StatMarketStats.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.StatMarketStats} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketStats.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getBasketcode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTotalfloorshares();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotaldeclineshares();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalnochangeshares();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotaladvanceshares();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalceilingshares();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getContributionstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      proto.mktservice.StatMarketContributionDetail.serializeBinaryToWriter
    );
  }
  f = message.getScalestatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      21,
      f,
      proto.mktservice.StatMarketScaleDetail.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp Date = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.mktservice.StatMarketStats.prototype.getDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.mktservice.StatMarketStats.prototype.setDate = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.mktservice.StatMarketStats.prototype.clearDate = function() {
  this.setDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketStats.prototype.hasDate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string BasketCode = 3;
 * @return {string}
 */
proto.mktservice.StatMarketStats.prototype.getBasketcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.mktservice.StatMarketStats.prototype.setBasketcode = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional EMarketStatsType Type = 4;
 * @return {!proto.mktservice.EMarketStatsType}
 */
proto.mktservice.StatMarketStats.prototype.getType = function() {
  return /** @type {!proto.mktservice.EMarketStatsType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.mktservice.EMarketStatsType} value */
proto.mktservice.StatMarketStats.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional google.protobuf.Int64Value TotalFloorShares = 5;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.StatMarketStats.prototype.getTotalfloorshares = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 5));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.StatMarketStats.prototype.setTotalfloorshares = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.mktservice.StatMarketStats.prototype.clearTotalfloorshares = function() {
  this.setTotalfloorshares(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketStats.prototype.hasTotalfloorshares = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Int64Value TotalDeclineShares = 6;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.StatMarketStats.prototype.getTotaldeclineshares = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 6));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.StatMarketStats.prototype.setTotaldeclineshares = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.mktservice.StatMarketStats.prototype.clearTotaldeclineshares = function() {
  this.setTotaldeclineshares(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketStats.prototype.hasTotaldeclineshares = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Int64Value TotalNoChangeShares = 7;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.StatMarketStats.prototype.getTotalnochangeshares = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 7));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.StatMarketStats.prototype.setTotalnochangeshares = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.mktservice.StatMarketStats.prototype.clearTotalnochangeshares = function() {
  this.setTotalnochangeshares(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketStats.prototype.hasTotalnochangeshares = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Int64Value TotalAdvanceShares = 8;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.StatMarketStats.prototype.getTotaladvanceshares = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 8));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.StatMarketStats.prototype.setTotaladvanceshares = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.mktservice.StatMarketStats.prototype.clearTotaladvanceshares = function() {
  this.setTotaladvanceshares(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketStats.prototype.hasTotaladvanceshares = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Int64Value TotalCeilingShares = 9;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.StatMarketStats.prototype.getTotalceilingshares = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 9));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.StatMarketStats.prototype.setTotalceilingshares = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.mktservice.StatMarketStats.prototype.clearTotalceilingshares = function() {
  this.setTotalceilingshares(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketStats.prototype.hasTotalceilingshares = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated StatMarketContributionDetail ContributionStats = 20;
 * @return {!Array<!proto.mktservice.StatMarketContributionDetail>}
 */
proto.mktservice.StatMarketStats.prototype.getContributionstatsList = function() {
  return /** @type{!Array<!proto.mktservice.StatMarketContributionDetail>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mktservice.StatMarketContributionDetail, 20));
};


/** @param {!Array<!proto.mktservice.StatMarketContributionDetail>} value */
proto.mktservice.StatMarketStats.prototype.setContributionstatsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.mktservice.StatMarketContributionDetail=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mktservice.StatMarketContributionDetail}
 */
proto.mktservice.StatMarketStats.prototype.addContributionstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.mktservice.StatMarketContributionDetail, opt_index);
};


proto.mktservice.StatMarketStats.prototype.clearContributionstatsList = function() {
  this.setContributionstatsList([]);
};


/**
 * repeated StatMarketScaleDetail ScaleStats = 21;
 * @return {!Array<!proto.mktservice.StatMarketScaleDetail>}
 */
proto.mktservice.StatMarketStats.prototype.getScalestatsList = function() {
  return /** @type{!Array<!proto.mktservice.StatMarketScaleDetail>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mktservice.StatMarketScaleDetail, 21));
};


/** @param {!Array<!proto.mktservice.StatMarketScaleDetail>} value */
proto.mktservice.StatMarketStats.prototype.setScalestatsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 21, value);
};


/**
 * @param {!proto.mktservice.StatMarketScaleDetail=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mktservice.StatMarketScaleDetail}
 */
proto.mktservice.StatMarketStats.prototype.addScalestats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 21, opt_value, proto.mktservice.StatMarketScaleDetail, opt_index);
};


proto.mktservice.StatMarketStats.prototype.clearScalestatsList = function() {
  this.setScalestatsList([]);
};


goog.object.extend(exports, proto.mktservice);
