/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
var common_data_common_pb = require('../common/data_common_pb.js');
goog.exportSymbol('proto.mktservice.EADIndicatorCategory', null, global);
goog.exportSymbol('proto.mktservice.StatMarketADDetail', null, global);
goog.exportSymbol('proto.mktservice.StatMarketADIndicator', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.StatMarketADDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mktservice.StatMarketADDetail.repeatedFields_, null);
};
goog.inherits(proto.mktservice.StatMarketADDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.StatMarketADDetail.displayName = 'proto.mktservice.StatMarketADDetail';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mktservice.StatMarketADDetail.repeatedFields_ = [5,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.StatMarketADDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.StatMarketADDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.StatMarketADDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketADDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    date: (f = msg.getDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    category: jspb.Message.getFieldWithDefault(msg, 2, 0),
    tickersList: jspb.Message.getRepeatedField(msg, 5),
    valuesList: jspb.Message.toObjectList(msg.getValuesList(),
    google_protobuf_wrappers_pb.DoubleValue.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.StatMarketADDetail}
 */
proto.mktservice.StatMarketADDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.StatMarketADDetail;
  return proto.mktservice.StatMarketADDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.StatMarketADDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.StatMarketADDetail}
 */
proto.mktservice.StatMarketADDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDate(value);
      break;
    case 2:
      var value = /** @type {!proto.mktservice.EADIndicatorCategory} */ (reader.readEnum());
      msg.setCategory(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addTickers(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.addValues(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.StatMarketADDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.StatMarketADDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.StatMarketADDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketADDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCategory();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getTickersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getValuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp Date = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.mktservice.StatMarketADDetail.prototype.getDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.mktservice.StatMarketADDetail.prototype.setDate = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.mktservice.StatMarketADDetail.prototype.clearDate = function() {
  this.setDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketADDetail.prototype.hasDate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional EADIndicatorCategory Category = 2;
 * @return {!proto.mktservice.EADIndicatorCategory}
 */
proto.mktservice.StatMarketADDetail.prototype.getCategory = function() {
  return /** @type {!proto.mktservice.EADIndicatorCategory} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.mktservice.EADIndicatorCategory} value */
proto.mktservice.StatMarketADDetail.prototype.setCategory = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * repeated string Tickers = 5;
 * @return {!Array<string>}
 */
proto.mktservice.StatMarketADDetail.prototype.getTickersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.mktservice.StatMarketADDetail.prototype.setTickersList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.mktservice.StatMarketADDetail.prototype.addTickers = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.mktservice.StatMarketADDetail.prototype.clearTickersList = function() {
  this.setTickersList([]);
};


/**
 * repeated google.protobuf.DoubleValue Values = 8;
 * @return {!Array<!proto.google.protobuf.DoubleValue>}
 */
proto.mktservice.StatMarketADDetail.prototype.getValuesList = function() {
  return /** @type{!Array<!proto.google.protobuf.DoubleValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 8));
};


/** @param {!Array<!proto.google.protobuf.DoubleValue>} value */
proto.mktservice.StatMarketADDetail.prototype.setValuesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.google.protobuf.DoubleValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.DoubleValue}
 */
proto.mktservice.StatMarketADDetail.prototype.addValues = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.google.protobuf.DoubleValue, opt_index);
};


proto.mktservice.StatMarketADDetail.prototype.clearValuesList = function() {
  this.setValuesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mktservice.StatMarketADIndicator = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mktservice.StatMarketADIndicator.repeatedFields_, null);
};
goog.inherits(proto.mktservice.StatMarketADIndicator, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mktservice.StatMarketADIndicator.displayName = 'proto.mktservice.StatMarketADIndicator';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mktservice.StatMarketADIndicator.repeatedFields_ = [7,8,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mktservice.StatMarketADIndicator.prototype.toObject = function(opt_includeInstance) {
  return proto.mktservice.StatMarketADIndicator.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mktservice.StatMarketADIndicator} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketADIndicator.toObject = function(includeInstance, msg) {
  var f, obj = {
    date: (f = msg.getDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    category: jspb.Message.getFieldWithDefault(msg, 2, 0),
    totaltickers: (f = msg.getTotaltickers()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totaladvance: (f = msg.getTotaladvance()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totalnochange: (f = msg.getTotalnochange()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    totaldecline: (f = msg.getTotaldecline()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f),
    lablesList: jspb.Message.getRepeatedField(msg, 7),
    valuesList: jspb.Message.toObjectList(msg.getValuesList(),
    google_protobuf_wrappers_pb.Int64Value.toObject, includeInstance),
    colorsList: jspb.Message.getRepeatedField(msg, 9)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mktservice.StatMarketADIndicator}
 */
proto.mktservice.StatMarketADIndicator.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mktservice.StatMarketADIndicator;
  return proto.mktservice.StatMarketADIndicator.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mktservice.StatMarketADIndicator} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mktservice.StatMarketADIndicator}
 */
proto.mktservice.StatMarketADIndicator.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDate(value);
      break;
    case 2:
      var value = /** @type {!proto.mktservice.EADIndicatorCategory} */ (reader.readEnum());
      msg.setCategory(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotaltickers(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotaladvance(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotalnochange(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setTotaldecline(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addLables(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.addValues(value);
      break;
    case 9:
      var value = /** @type {!Array<!proto.mktservice.EMarketColorCode>} */ (reader.readPackedEnum());
      msg.setColorsList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mktservice.StatMarketADIndicator.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mktservice.StatMarketADIndicator.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mktservice.StatMarketADIndicator} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mktservice.StatMarketADIndicator.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCategory();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getTotaltickers();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotaladvance();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotalnochange();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getTotaldecline();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getLablesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getValuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
  f = message.getColorsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      9,
      f
    );
  }
};


/**
 * optional google.protobuf.Timestamp Date = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.mktservice.StatMarketADIndicator.prototype.getDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.mktservice.StatMarketADIndicator.prototype.setDate = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.mktservice.StatMarketADIndicator.prototype.clearDate = function() {
  this.setDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketADIndicator.prototype.hasDate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional EADIndicatorCategory Category = 2;
 * @return {!proto.mktservice.EADIndicatorCategory}
 */
proto.mktservice.StatMarketADIndicator.prototype.getCategory = function() {
  return /** @type {!proto.mktservice.EADIndicatorCategory} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.mktservice.EADIndicatorCategory} value */
proto.mktservice.StatMarketADIndicator.prototype.setCategory = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional google.protobuf.Int64Value TotalTickers = 3;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.StatMarketADIndicator.prototype.getTotaltickers = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 3));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.StatMarketADIndicator.prototype.setTotaltickers = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.mktservice.StatMarketADIndicator.prototype.clearTotaltickers = function() {
  this.setTotaltickers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketADIndicator.prototype.hasTotaltickers = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Int64Value TotalAdvance = 4;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.StatMarketADIndicator.prototype.getTotaladvance = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 4));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.StatMarketADIndicator.prototype.setTotaladvance = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.mktservice.StatMarketADIndicator.prototype.clearTotaladvance = function() {
  this.setTotaladvance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketADIndicator.prototype.hasTotaladvance = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Int64Value TotalNoChange = 5;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.StatMarketADIndicator.prototype.getTotalnochange = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 5));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.StatMarketADIndicator.prototype.setTotalnochange = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.mktservice.StatMarketADIndicator.prototype.clearTotalnochange = function() {
  this.setTotalnochange(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketADIndicator.prototype.hasTotalnochange = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Int64Value TotalDecline = 6;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.mktservice.StatMarketADIndicator.prototype.getTotaldecline = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 6));
};


/** @param {?proto.google.protobuf.Int64Value|undefined} value */
proto.mktservice.StatMarketADIndicator.prototype.setTotaldecline = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.mktservice.StatMarketADIndicator.prototype.clearTotaldecline = function() {
  this.setTotaldecline(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.mktservice.StatMarketADIndicator.prototype.hasTotaldecline = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated string Lables = 7;
 * @return {!Array<string>}
 */
proto.mktservice.StatMarketADIndicator.prototype.getLablesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/** @param {!Array<string>} value */
proto.mktservice.StatMarketADIndicator.prototype.setLablesList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.mktservice.StatMarketADIndicator.prototype.addLables = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


proto.mktservice.StatMarketADIndicator.prototype.clearLablesList = function() {
  this.setLablesList([]);
};


/**
 * repeated google.protobuf.Int64Value Values = 8;
 * @return {!Array<!proto.google.protobuf.Int64Value>}
 */
proto.mktservice.StatMarketADIndicator.prototype.getValuesList = function() {
  return /** @type{!Array<!proto.google.protobuf.Int64Value>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 8));
};


/** @param {!Array<!proto.google.protobuf.Int64Value>} value */
proto.mktservice.StatMarketADIndicator.prototype.setValuesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.google.protobuf.Int64Value=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Int64Value}
 */
proto.mktservice.StatMarketADIndicator.prototype.addValues = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.google.protobuf.Int64Value, opt_index);
};


proto.mktservice.StatMarketADIndicator.prototype.clearValuesList = function() {
  this.setValuesList([]);
};


/**
 * repeated EMarketColorCode Colors = 9;
 * @return {!Array<!proto.mktservice.EMarketColorCode>}
 */
proto.mktservice.StatMarketADIndicator.prototype.getColorsList = function() {
  return /** @type {!Array<!proto.mktservice.EMarketColorCode>} */ (jspb.Message.getRepeatedField(this, 9));
};


/** @param {!Array<!proto.mktservice.EMarketColorCode>} value */
proto.mktservice.StatMarketADIndicator.prototype.setColorsList = function(value) {
  jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {!proto.mktservice.EMarketColorCode} value
 * @param {number=} opt_index
 */
proto.mktservice.StatMarketADIndicator.prototype.addColors = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


proto.mktservice.StatMarketADIndicator.prototype.clearColorsList = function() {
  this.setColorsList([]);
};


/**
 * @enum {number}
 */
proto.mktservice.EADIndicatorCategory = {
  EAD_UNK: 0,
  EAD_ALL: 1,
  EAD_VNINDEX: 2,
  EAD_HNXINDEX: 3,
  EAD_UPCOMINDEX: 4,
  EAD_VN30: 5
};

goog.object.extend(exports, proto.mktservice);
